/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import dao.UserDAO;
import entity.User;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import support.Formatacao;
import support.Validacao;

/**
 *
 * @author dudub
 */
public class IfrUserRegister extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrCadastroUsuario
     */
    public IfrUserRegister() {
        initComponents();
        tfdIdCadUsuarios.setText("0");
        tfdIdCadUsuarios.setEditable(false);
        Formatacao.formatarData(tfdBirthDate);
        Formatacao.formatarCpf(tfdCpf);
        Formatacao.formatarTelefone(tfdPhone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadUser = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnClearFields = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfdName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfdIdCadUsuarios = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfdPesquisarCadUsuarios = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        tfdEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        tfdBirthDate = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        ComboGenre = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        ComboStatus = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        tfdCpf = new javax.swing.JFormattedTextField();
        tfdPhone = new javax.swing.JFormattedTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("User Search");

        jTableCadUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Login", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCadUser);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("User Register");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSalvar.setText("Save");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnClearFields.setText("Clear Fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Password");

        jLabel7.setText("Id");

        jLabel8.setText("Search");

        btnPesquisar.setText("Search");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel13.setText("Email");

        jLabel14.setText("CPF");

        jLabel15.setText("Phone");

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        tfdBirthDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdBirthDateActionPerformed(evt);
            }
        });

        jLabel16.setText("Birth Date");

        ComboGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Neutral" }));
        ComboGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGenreActionPerformed(evt);
            }
        });

        jLabel17.setText("Genre");

        ComboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        jLabel18.setText("Status");

        tfdCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdCpfActionPerformed(evt);
            }
        });

        tfdPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(147, 147, 147)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfdPesquisarCadUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfdIdCadUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdBirthDate)
                            .addComponent(tfdEmail)
                            .addComponent(tfdName)
                            .addComponent(jPassword)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ComboGenre, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                                .addComponent(btnClearFields)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSalvar)
                                    .addComponent(btnClose))
                                .addGap(5, 5, 5))
                            .addComponent(tfdCpf)
                            .addComponent(tfdPhone, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfdPesquisarCadUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfdIdCadUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfdCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfdPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(btnClearFields)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClose)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
            
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // cria instancia usuario
        String birthdate = tfdBirthDate.getText();
        User u = new User();
        Validacao valida = new Validacao();
        //cria variavel auxilar
        char auxiliar = 'S';
        String idaux = tfdIdCadUsuarios.getText();
        int idaux1 = Integer.parseInt(idaux);
        String a = tfdName.getText();
        String b = tfdEmail.getText();
        String c = jPassword.getText();
        String d = tfdCpf.getText().replace(".", "").replace("-", "");
        String e = tfdPhone.getText().replace("(", "").replace("-", "").replace(")", "");
        int g = ComboGenre.getSelectedIndex();
        int h = ComboStatus.getSelectedIndex();
        String senhaaux = "";
        // int d = Integer.parseInt(tfdStatusCadUsuarios.getText());
        int igual = 5; // indicador que confere se a senha ao editar é igual a antiga
        UserDAO uDAO = new UserDAO();
        //validação
        if (a.isEmpty()) { //Verifica se o campo Nome está vazio.
            System.out.println("Nome em branco!");
            JOptionPane.showMessageDialog(null, "The field name should be filled!");
            auxiliar = 'N';
            limparCampos();
        } else {
            if (b.isEmpty()) { //Verifica se o campo Email esta vazio.
                System.out.println("Email em branco! ");
                JOptionPane.showMessageDialog(null, "The field email should be filled!");
                auxiliar = 'N';
                limparCampos();
            } else {
                if (c.isEmpty()) { //Verifica se o Senha status está vazio!
                    System.out.println("Senha em branco! ");
                    JOptionPane.showMessageDialog(null, "The field password should be filled!");
                    auxiliar = 'N';
                    limparCampos();
                } else {
                    if (d.isEmpty()) { //Verifica se o campo CPF está vazio!
                        System.out.println("cpffff" + d);
                        System.out.println("The field CPF should be filled! ");
                        JOptionPane.showMessageDialog(null, "The field CPF should be filled!");
                        auxiliar = 'N';
                        limparCampos();
                    } else {
                        if (e.isEmpty()) { //Verifica se o campo Telefone está vazio!
                            System.out.println("The field phone should be filled! ");
                            JOptionPane.showMessageDialog(null, "The field phone should be filled!");
                            auxiliar = 'N';
                            limparCampos();
                        } else {
                            if (valida.validarDataFormatada(birthdate) == false) {
                                System.out.println("Invalid Date");
                                JOptionPane.showMessageDialog(null, "The date informed is invalid!");
                                auxiliar = 'N';
                                limparCampos();
                            } else {
                                if (ComboGenre.getSelectedIndex() == 0) {
                                    System.out.println("Genre not selected");
                                    JOptionPane.showMessageDialog(null, "Please select a Genre!");
                                    auxiliar = 'N';
                                    limparCampos();
                                } else {
                                    if (ComboGenre.getSelectedIndex() == 0) {
                                        System.out.println("Genre not selected");
                                        JOptionPane.showMessageDialog(null, "Please select a Genre!");
                                        auxiliar = 'N';
                                        limparCampos();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        // popular o objeto
           
        if (auxiliar == 'S') {
            u.setId(idaux1);
            u.setName(a);
            u.setEmail(b);
            u.setPassword(c);
            u.setCpf(d);
            u.setPhone(e);
            u.setBirthdate(birthdate);
            if (g == 1) {
                u.setGenre("M");
            } else if (g == 2) {
                u.setGenre("F");
            } else {
                u.setGenre("N");
            }
            if (h == 0) {
                u.setActive("A");
            } else {
                u.setActive("I");
            }
            
            if (idaux1 != 0 ) {
                senhaaux = jPassword.getText();
                if (uDAO.returnpassword(idaux1).equals(senhaaux)) {
                    igual = 0;
                } else {
                    igual = 1; 
                };
            }
            
            
            // cadastrar com senha
            
            if (igual == 0) {
                uDAO.setDataStyle();
                if (uDAO.savewithoutmd5(u)) {
                    if (idaux1 == 0) {
                        JOptionPane.showMessageDialog(this, "Record was successfully saved!");
                        limparCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "Record was successfully edited!");
                        limparCampos();
                    }
                }
            } else {
                uDAO.setDataStyle();
                if (uDAO.save(u)) {
                    if (idaux1 == 0) {
                        JOptionPane.showMessageDialog(this, "Record was successfully saved!");
                        limparCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "Record was successfully edited!");
                        limparCampos();
                    } 
                }
            }
            
            
            uDAO.popularTabela(jTableCadUser, tfdPesquisarCadUsuarios.getText());
            //limpa os campos
            limparCampos();
            tfdName.requestFocus();
            
            
            
            auxiliar = 'S';
        }
        

    
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void limparCampos () {
        tfdIdCadUsuarios.setText("0");
        tfdName.setText("");
        tfdEmail.setText("");
        jPassword.setText("");
        tfdCpf.setText("");
        tfdPhone.setText("");
        tfdBirthDate.setText("");
        ComboGenre.setSelectedIndex(0);
        ComboStatus.setSelectedIndex(0);
    }
    
    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        tfdIdCadUsuarios.setText("0");
        tfdName.setText("");
        tfdEmail.setText("");
        jPassword.setText("");
        tfdCpf.setText("");
        tfdPhone.setText("");
        tfdBirthDate.setText("");
        ComboGenre.setSelectedIndex(0);
        ComboStatus.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String idString = String.valueOf(jTableCadUser.getValueAt(jTableCadUser.getSelectedRow(), 0));
        int idS = Integer.parseInt(idString);
        int x;
        int z;
        tfdIdCadUsuarios.setEditable(false);
        // criar instancia SecaoDAO
        UserDAO uDAO = new UserDAO();

        // criar instancia Secao
        User usuario = uDAO.consultId(idS);
        if (usuario != null) {
            // define os valores do obj nos campos da tela
            tfdIdCadUsuarios.setText(""+usuario.getId());
            tfdName.setText(usuario.getName());
            tfdEmail.setText(usuario.getEmail());
            jPassword.setText(usuario.getPassword());
            tfdCpf.setText(usuario.getCpf());
            tfdPhone.setText(usuario.getPhone());
            tfdBirthDate.setText(usuario.getBirthdate());

            String f = usuario.getBirthdate();
            x = uDAO.consultComboGenre(usuario.getId());
            if (x == 1) {
                ComboGenre.setSelectedIndex(1);
            } else if (x == 2) {
                 ComboGenre.setSelectedIndex(2);
            } else {
                 ComboGenre.setSelectedIndex(3);
            }
            z = uDAO.consultComboActive(usuario.getId());
            if (z == 1) {
                ComboStatus.setSelectedIndex(0);
            } else {
                ComboStatus.setSelectedIndex(1);
            }
            uDAO.popularTabela(jTableCadUser, tfdPesquisarCadUsuarios.getText());
            tfdName.requestFocus();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new UserDAO().popularTabela(jTableCadUser,tfdPesquisarCadUsuarios.getText());        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
           tfdIdCadUsuarios.setEditable(false);
            if (JOptionPane.showConfirmDialog(this, "Are you sure that you want to delete?") == JOptionPane.OK_OPTION) {
            
            
            String idString = String.valueOf(jTableCadUser.getValueAt(jTableCadUser.getSelectedRow(), 0));
                System.out.println(idString);
            int idExclusao = Integer.parseInt(idString);

            UserDAO uDAO = new UserDAO();
            
            if (uDAO.delete(idExclusao)) {
                JOptionPane.showMessageDialog(null, "User deleted sucessfully!");
                uDAO.popularTabela(jTableCadUser, tfdPesquisarCadUsuarios.getText());
            
            
            } else {
                JOptionPane.showMessageDialog(null, "Problems when deleting user");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    

   
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed

    }//GEN-LAST:event_btnCloseActionPerformed

    private void tfdBirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdBirthDateActionPerformed

    }//GEN-LAST:event_tfdBirthDateActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void ComboGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboGenreActionPerformed

    private void tfdCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdCpfActionPerformed

    private void tfdPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdPhoneActionPerformed


   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboGenre;
    private javax.swing.JComboBox<String> ComboStatus;
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadUser;
    private javax.swing.JFormattedTextField tfdBirthDate;
    private javax.swing.JFormattedTextField tfdCpf;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdIdCadUsuarios;
    private javax.swing.JTextField tfdName;
    private javax.swing.JTextField tfdPesquisarCadUsuarios;
    private javax.swing.JFormattedTextField tfdPhone;
    // End of variables declaration//GEN-END:variables
}
