/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import dao.UserDAO;
import entity.User;
import javax.swing.JOptionPane;
import support.Formatacao;
import support.Validacao;

/**
 *
 * @author dudub
 */
public class JFrameUserRegister extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JFrameUserRegister() {
        initComponents();
        tfdIdCadUsuarios.setText("0");
        tfdIdCadUsuarios.setEnabled(false);
        Formatacao.formatarData(tfdBirthDate);
        Formatacao.formatarCpf(tfdCpf);
        Formatacao.formatarTelefone(tfdPhone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfdName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfdIdCadUsuarios = new javax.swing.JTextField();
        tfdEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        tfdBirthDate = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        ComboGenre = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ComboStatus = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        tfdCpf = new javax.swing.JFormattedTextField();
        btnClearFields = new javax.swing.JButton();
        tfdPhone = new javax.swing.JFormattedTextField();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Password");

        jLabel7.setText("Id");

        tfdIdCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdIdCadUsuariosActionPerformed(evt);
            }
        });

        jLabel13.setText("Email");

        jLabel14.setText("CPF");

        jLabel15.setText("Phone");

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        tfdBirthDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdBirthDateActionPerformed(evt);
            }
        });

        jLabel16.setText("Birth Date");

        ComboGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Neutral" }));
        ComboGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGenreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("User Register");

        jLabel17.setText("Genre");

        ComboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        jLabel18.setText("Status");

        btnSalvar.setText("Save");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tfdCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdCpfActionPerformed(evt);
            }
        });

        btnClearFields.setText("Clear Fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        tfdPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdPhoneActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfdIdCadUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfdEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfdName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfdCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfdPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnClearFields)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSalvar))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(240, 240, 240)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(btnClose)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfdIdCadUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfdCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(tfdPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfdBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ComboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClearFields)
                            .addComponent(btnSalvar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void tfdBirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdBirthDateActionPerformed

    }//GEN-LAST:event_tfdBirthDateActionPerformed

    private void ComboGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboGenreActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // cria instancia usuario
        String birthdate = tfdBirthDate.getText();
        User u = new User();
        Validacao valida = new Validacao();
        //cria variavel auxilar
        char auxiliar = 'S';
        String idaux = tfdIdCadUsuarios.getText();
        int idaux1 = Integer.parseInt(idaux);
        String a = tfdName.getText();
        String b = tfdEmail.getText();
        String c = jPassword.getText();
        String d = tfdCpf.getText().replace(".", "").replace("-", "");
        String e = tfdPhone.getText().replace("(", "").replace("-", "").replace(")", "");
        int g = ComboGenre.getSelectedIndex();
        int h = ComboStatus.getSelectedIndex();
        String senhaaux = "";
        // int d = Integer.parseInt(tfdStatusCadUsuarios.getText());
        int igual = 5; // indicador que confere se a senha ao editar é igual a antiga
        UserDAO uDAO = new UserDAO();
        //validação
        if (a.isEmpty()) { //Verifica se o campo Nome está vazio.
            System.out.println("Nome em branco!");
            JOptionPane.showMessageDialog(null, "The field name should be filled!");
            auxiliar = 'N';
            limparCampos();
        } else {
            if (b.isEmpty()) { //Verifica se o campo Email esta vazio.
                System.out.println("Email em branco! ");
                JOptionPane.showMessageDialog(null, "The field email should be filled!");
                auxiliar = 'N';
                limparCampos();
            } else {
                if (c.isEmpty()) { //Verifica se o Senha status está vazio!
                    System.out.println("Senha em branco! ");
                    JOptionPane.showMessageDialog(null, "The field password should be filled!");
                    auxiliar = 'N';
                    limparCampos();
                } else {
                    if (d.isEmpty()) { //Verifica se o campo CPF está vazio!
                        System.out.println("cpffff" + d);
                        System.out.println("The field CPF should be filled! ");
                        JOptionPane.showMessageDialog(null, "The field CPF should be filled!");
                        auxiliar = 'N';
                        limparCampos();
                    } else {
                        if (e.isEmpty()) { //Verifica se o campo Telefone está vazio!
                            System.out.println("The field phone should be filled! ");
                            JOptionPane.showMessageDialog(null, "The field phone should be filled!");
                            auxiliar = 'N';
                            limparCampos();
                        } else {
                            if (valida.validarDataFormatada(birthdate) == false) {
                                System.out.println("Invalid Date");
                                JOptionPane.showMessageDialog(null, "The date informed is invalid!");
                                auxiliar = 'N';
                                limparCampos();
                            } else {
                                if (ComboGenre.getSelectedIndex() == 0) {
                                    System.out.println("Genre not selected");
                                    JOptionPane.showMessageDialog(null, "Please select a Genre!");
                                    auxiliar = 'N';
                                    limparCampos();
                                } else {
                                    if (ComboGenre.getSelectedIndex() == 0) {
                                        System.out.println("Genre not selected");
                                        JOptionPane.showMessageDialog(null, "Please select a Genre!");
                                        auxiliar = 'N';
                                        limparCampos();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        // popular o objeto

        if (auxiliar == 'S') {
            u.setId(idaux1);
            u.setName(a);
            u.setEmail(b);
            u.setPassword(c);
            u.setCpf(d);
            u.setPhone(e);
            u.setBirthdate(birthdate);
            if (g == 1) {
                u.setGenre("M");
            } else if (g == 2) {
                u.setGenre("F");
            } else {
                u.setGenre("N");
            }
            if (h == 0) {
                u.setActive("A");
            } else {
                u.setActive("I");
            }


            if (uDAO.consultCpf(d)) {
              uDAO.setDataStyle();
              uDAO.insertUserExceptCpf(u);
              JOptionPane.showMessageDialog(null, "User updated and registered sucessfully! \nCertificates of attended events are available in the system!");
              
            } else {
                uDAO.setDataStyle();
                uDAO.save(u);
                JOptionPane.showMessageDialog(null, "User registered sucessfully!");
            }
                    

            //limpa os campos
            limparCampos();
            tfdName.requestFocus();

            auxiliar = 'S';
        }

    }//GEN-LAST:event_btnSalvarActionPerformed
private void limparCampos () {
        tfdIdCadUsuarios.setText("0");
        tfdName.setText("");
        tfdEmail.setText("");
        jPassword.setText("");
        tfdCpf.setText("");
        tfdPhone.setText("");
        tfdBirthDate.setText("");
        ComboGenre.setSelectedIndex(0);
        ComboStatus.setSelectedIndex(0);
}
    
    
    
    
    private void tfdCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdCpfActionPerformed

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        tfdIdCadUsuarios.setText("0");
        tfdName.setText("");
        tfdEmail.setText("");
        jPassword.setText("");
        tfdCpf.setText("");
        tfdPhone.setText("");
        tfdBirthDate.setText("");
        ComboGenre.setSelectedIndex(0);
        ComboStatus.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void tfdPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdPhoneActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        new Login(null, true).setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tfdIdCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdIdCadUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdIdCadUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUserRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboGenre;
    private javax.swing.JComboBox<String> ComboStatus;
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JFormattedTextField tfdBirthDate;
    private javax.swing.JFormattedTextField tfdCpf;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdIdCadUsuarios;
    private javax.swing.JTextField tfdName;
    private javax.swing.JFormattedTextField tfdPhone;
    // End of variables declaration//GEN-END:variables
}
